[project]
name = "python-mastery"
version = "0.1.0"
description = "My road to Python's mastery"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "ipykernel>=6.30.0",
    "pandas>=2.3.1",
    "requests>=2.32.4",
]
